@host = http://localhost:3000

#############
## AUTHORS ##
#############

# Request to get all authors
GET {{host}}/api/author

###

# Request to get a specific author by ID
GET {{host}}/api/author/1

###

# Request to get all posts by a specific author
GET {{host}}/api/author/6/posts

###

# Request to create a new author
POST {{host}}/api/author
Content-Type: application/json

{
    "name": "Charles Smith",
    "email": "charles.smith4@example.com",
    "image": "https://example.com/charles.jpg"
}

###

# Request to update an existing author
PUT {{host}}/api/author/1
Content-Type: application/json

{
    "name": "Tom Marshall",
    "email": "tom.marshall@example.com",
    "image": "https://example.com/tom.jpg"
}

###

# Request to delete an author
DELETE {{host}}/api/author/9

###########
## POSTS ##
###########

# Request to get all posts
GET {{host}}/api/post

###

# Request to get a specific post by ID
GET {{host}}/api/post/15

###

# Request to create a new post
POST {{host}}/api/post
Content-Type: application/json

{
    "title": "Homemade Pizza Secrets",
    "description": "Tips and tricks for making delicious pizza at home.",
    "category": "Food",
    "author_id": 1
}

###

# Request to update an existing post
PUT {{host}}/api/post/13
Content-Type: application/json

{
    "title": "Homemade Pizza Secrets",
    "description": "Tips and tricks for making delicious pizza at home.",
    "category": "Food",
    "author_id": 2
}

###

# Request to delete a post
DELETE {{host}}/api/post/14